syntax = "proto3";

package purchase;

import "google/api/annotations.proto";

option go_package = "./pb";

service PurchaseService {
  rpc Checkout(CheckoutRequest) returns (CheckoutResponse) {
    option (google.api.http) = {
      post: "/api/cart/checkout"
      body: "*"
    };
  }
  rpc GetCart(GetCartRequest) returns (GetCartResponse) {
    option (google.api.http) = {
      get: "/api/cart"
    };
  }
}

message CheckoutRequest {
  string user_id = 1;
}

message CheckoutResponse {
  repeated TourPurchaseToken tokens = 1;
  string message = 2;
}

message GetCartRequest {
  string user_id = 1;
}

message GetCartResponse {
  string id = 1;
  string tourist_id = 2;
  repeated CartItem items = 3;
  double total = 4;
}

message CartItem {
  string id = 1;
  string tour_id = 2;
  string name = 3;
  double price = 4;
}

message TourPurchaseToken {
  string tour_id = 1;
  string tourist_id = 2;
  string token = 3;
  string created_at = 4;
}