version: "3.9"

services:
  blog-db:
    image: postgres:15
    container_name: blog-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog
    ports:
      - "5432:5432"
    volumes:
      - blog-data:/var/lib/postgresql/data

  blog-service:
    build: .
    container_name: blog-service
    environment:
      DB_HOST: blog-db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: blog
      DB_PORT: 5432
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - blog-db

volumes:
  blog-data:
