version: "3.9"

services:
  stakeholders-db:
    image: postgres:15
    container_name: stakeholders-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super
      POSTGRES_DB: stakeholdersdb
    ports:
      - "5433:5432"
    volumes:
      - stakeholders-data:/var/lib/postgresql/data

  stakeholders-service:
    build:
      context: ./services/stakeholders
      dockerfile: Dockerfile
    container_name: stakeholders-service
    environment:
      DB_HOST: stakeholders-db
      DB_USER: postgres
      DB_PASSWORD: super
      DB_NAME: stakeholdersdb
      DB_PORT: 5432
      PORT: 8080
    ports:
      - "8082:8080"
    depends_on:
      - stakeholders-db

volumes:
  stakeholders-data:
