version: "3.9"

services:
  stakeholders-db:
    image: postgres:15
    container_name: stakeholders-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super
      POSTGRES_DB: stakeholdersdb
    ports:
      - "5433:5432"
    volumes:
      - stakeholders-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  stakeholders-service:
    build:
      context: ./services/stakeholders
      dockerfile: Dockerfile
    container_name: stakeholders-service
    environment:
      DB_HOST: stakeholders-db
      DB_USER: postgres
      DB_PASSWORD: super
      DB_NAME: stakeholdersdb
      DB_PORT: 5432
      PORT: 8080
    ports:
      - "8082:8080"
    depends_on:
      stakeholders-db:
        condition: service_healthy


  tour-db:
    image: postgres:15
    container_name: tour-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super
      POSTGRES_DB: tourdb
    ports:
      - "5434:5432"
    volumes:
      - tour-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  tour-service:
    build:
      context: ./services/tour
      dockerfile: Dockerfile
    container_name: tour-service
    environment:
      DB_HOST: tour-db
      DB_USER: postgres
      DB_PASSWORD: super
      DB_NAME: tourdb
      DB_PORT: 5432
      PORT: 8080
    ports:
      - "8083:8080"
    depends_on:
      tour-db:
         condition: service_healthy

volumes:
  stakeholders-data:
  tour-data:
