// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/purchase.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutRequest) Reset() {
	*x = CheckoutRequest{}
	mi := &file_proto_purchase_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutRequest) ProtoMessage() {}

func (x *CheckoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutRequest.ProtoReflect.Descriptor instead.
func (*CheckoutRequest) Descriptor() ([]byte, []int) {
	return file_proto_purchase_proto_rawDescGZIP(), []int{0}
}

func (x *CheckoutRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CheckoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []*TourPurchaseToken   `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutResponse) Reset() {
	*x = CheckoutResponse{}
	mi := &file_proto_purchase_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutResponse) ProtoMessage() {}

func (x *CheckoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutResponse.ProtoReflect.Descriptor instead.
func (*CheckoutResponse) Descriptor() ([]byte, []int) {
	return file_proto_purchase_proto_rawDescGZIP(), []int{1}
}

func (x *CheckoutResponse) GetTokens() []*TourPurchaseToken {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *CheckoutResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TourPurchaseToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	TouristId     string                 `protobuf:"bytes,2,opt,name=tourist_id,json=touristId,proto3" json:"tourist_id,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TourPurchaseToken) Reset() {
	*x = TourPurchaseToken{}
	mi := &file_proto_purchase_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourPurchaseToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourPurchaseToken) ProtoMessage() {}

func (x *TourPurchaseToken) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourPurchaseToken.ProtoReflect.Descriptor instead.
func (*TourPurchaseToken) Descriptor() ([]byte, []int) {
	return file_proto_purchase_proto_rawDescGZIP(), []int{2}
}

func (x *TourPurchaseToken) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *TourPurchaseToken) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

func (x *TourPurchaseToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TourPurchaseToken) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_proto_purchase_proto protoreflect.FileDescriptor

const file_proto_purchase_proto_rawDesc = "" +
	"\n" +
	"\x14proto/purchase.proto\x12\bpurchase\"*\n" +
	"\x0fCheckoutRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"a\n" +
	"\x10CheckoutResponse\x123\n" +
	"\x06tokens\x18\x01 \x03(\v2\x1b.purchase.TourPurchaseTokenR\x06tokens\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x80\x01\n" +
	"\x11TourPurchaseToken\x12\x17\n" +
	"\atour_id\x18\x01 \x01(\tR\x06tourId\x12\x1d\n" +
	"\n" +
	"tourist_id\x18\x02 \x01(\tR\ttouristId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt2T\n" +
	"\x0fPurchaseService\x12A\n" +
	"\bCheckout\x12\x19.purchase.CheckoutRequest\x1a\x1a.purchase.CheckoutResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_proto_purchase_proto_rawDescOnce sync.Once
	file_proto_purchase_proto_rawDescData []byte
)

func file_proto_purchase_proto_rawDescGZIP() []byte {
	file_proto_purchase_proto_rawDescOnce.Do(func() {
		file_proto_purchase_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_purchase_proto_rawDesc), len(file_proto_purchase_proto_rawDesc)))
	})
	return file_proto_purchase_proto_rawDescData
}

var file_proto_purchase_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_purchase_proto_goTypes = []any{
	(*CheckoutRequest)(nil),   // 0: purchase.CheckoutRequest
	(*CheckoutResponse)(nil),  // 1: purchase.CheckoutResponse
	(*TourPurchaseToken)(nil), // 2: purchase.TourPurchaseToken
}
var file_proto_purchase_proto_depIdxs = []int32{
	2, // 0: purchase.CheckoutResponse.tokens:type_name -> purchase.TourPurchaseToken
	0, // 1: purchase.PurchaseService.Checkout:input_type -> purchase.CheckoutRequest
	1, // 2: purchase.PurchaseService.Checkout:output_type -> purchase.CheckoutResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_purchase_proto_init() }
func file_proto_purchase_proto_init() {
	if File_proto_purchase_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_purchase_proto_rawDesc), len(file_proto_purchase_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_purchase_proto_goTypes,
		DependencyIndexes: file_proto_purchase_proto_depIdxs,
		MessageInfos:      file_proto_purchase_proto_msgTypes,
	}.Build()
	File_proto_purchase_proto = out.File
	file_proto_purchase_proto_goTypes = nil
	file_proto_purchase_proto_depIdxs = nil
}
