version: "3.9"

services:
  neo4j:
    image: neo4j:5
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/supersecret"
    volumes:
      - neo4j-data:/data   # čuva podatke Neo4j trajno

  follow-service:
    build: .
    container_name: follow-service
    ports:
      - "8000:8000"
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: supersecret
    depends_on:
      - neo4j
    volumes:
      - ./app:/app   # development hot-reload (vidi promene odmah)

volumes:
  neo4j-data:
