{
 "title": "Kontejner",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "read/write u MB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_fs_reads_bytes_total{}[1m]) / 1024 / 1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(container_fs_writes_bytes_total{}[1m]) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process network transmit u kb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_network_transmit_bytes_total{instance=\"blog-service:8080\"}[1m]) / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "network transmit/receive app u kb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{}[1m]) / 1024 ",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(container_network_receive_bytes_total{}[1m]) / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cpu seconds total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(process_network_receive_bytes_total{instance=\"blog-service:8080\"}[1m]) / 1024 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ram gb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ram u mb blog servisa",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{container=\"blog-service\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_resident_memory_bytes{instance=\"blog-service:8080\"} / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}